// Package chat implements a real-time chat server with WebSocket messaging,
// message history, full-text search, and session management.
//
// All messages and user sessions are held entirely in memory and are lost
// on server restart.
package chat

import "time"

// Message type constants used as the "type" field in ClientRequest and
// ServerResponse JSON payloads.
const (
	MessageTypeChat    = "chat"    // send a chat message to a recipient
	MessageTypeHistory = "history" // request conversation history
	MessageTypeSearch  = "search"  // full-text search across messages
	MessageTypeError   = "error"   // server-side error response
)

// UserSession represents an authenticated user session.
// Connected is true while a WebSocket connection is active; it is set
// to false on disconnect and the session is deleted entirely on logout.
type UserSession struct {
	Username    string    `json:"username"`
	Connected   bool      `json:"connected"`
	ConnectedAt time.Time `json:"connectedAt"`
}

// Message is a single chat message exchanged between two users.
// MessageID is a UUID v4 generated by the server.
type Message struct {
	MessageID string    `json:"messageId"`
	Sender    string    `json:"sender"`
	Recipient string    `json:"recipient"`
	Text      string    `json:"text"`
	Timestamp time.Time `json:"timestamp"`
}

// ClientRequest is the JSON payload the client sends over the WebSocket.
// The Sender field is set by the server from the authenticated username
// and should not be trusted from the client.
type ClientRequest struct {
	Type      string `json:"type"`             // one of the MessageType* constants
	Sender    string `json:"sender,omitempty"` // overwritten by server
	Recipient string `json:"recipient,omitempty"`
	Text      string `json:"text,omitempty"`
	Query     string `json:"query,omitempty"`
}

// ServerResponse is the JSON payload the server sends to a client over
// the WebSocket.  Exactly one of Message, Messages, or Error will be set
// depending on the response Type.
type ServerResponse struct {
	Type     string    `json:"type"`
	Message  *Message  `json:"message,omitempty"`
	Messages []Message `json:"messages,omitempty"`
	Error    string    `json:"error,omitempty"`
}
